import { ViteSSG } from 'vite-ssg/single-page'
// Только латиница и кириллица — остальные сабсеты (greek, vietnamese, …) сайту не нужны
import '@fontsource/inter/latin-400.css'
import '@fontsource/inter/cyrillic-400.css'
import '@fontsource/inter/latin-500.css'
import '@fontsource/inter/cyrillic-500.css'
import '@fontsource/inter/latin-600.css'
import '@fontsource/inter/cyrillic-600.css'
import '@fontsource/jetbrains-mono/latin-400.css'
import '@fontsource/jetbrains-mono/cyrillic-400.css'
import '@fontsource/jetbrains-mono/latin-500.css'
import '@fontsource/jetbrains-mono/cyrillic-500.css'
import '@fontsource/jetbrains-mono/latin-600.css'
import '@fontsource/jetbrains-mono/cyrillic-600.css'
import '@fontsource/jetbrains-mono/latin-700.css'
import '@fontsource/jetbrains-mono/cyrillic-700.css'
import './style.css'
import App from './App.vue'

export const createApp = ViteSSG(App)
